const id = "aws.md";
						const collection = "blog";
						const slug = "aws";
						const body = "#### If you've been hesitant to learn cloud computing, well today is your day to sign up and get your hands on.\r\n\r\n\r\n### How to Get Started with AWS for Free\r\n\r\nAs a developer, it's important to be cloud-competent. AWS is a popular cloud platform, and it offers a free tier that you can use to learn the basics.\r\n\r\n### Creating an AWS Account\r\nTo get started, you'll need to create an AWS account. You can do this by going to https://aws.amazon.com/ and clicking on the \"Create an AWS Account\" button\r\n\r\n### Setting Up Your Account\r\nOnce you have created an account, you'll need to set up your billing information. You can do this by going to the \"Billing\" section of the AWS Management Console.\r\n\r\n\r\n### Enabling Billing Alerts\r\nIt's a good idea to enable billing alerts so that you're notified if your costs start to exceed your budget. You can do this by going to the \"Billing Preferences\" section of the AWS Management Console.\r\n\r\n\r\n### Creating a User\r\nYou should not use the root user account for everyday tasks. Instead, you should create a separate user account with administrative privileges. You can do this by going to the \"IAM\" section of the AWS Management Console.\r\n\r\n\r\n### Setting Up MFA\r\nIt's important to enable multi-factor authentication (MFA) for your user account. This will help to protect your account from unauthorized access. You can enable MFA by going to the \"Security Credentials\" section of the AWS Management Console.\r\n\r\n### Installing the AWS CLI\r\nThe AWS CLI is a command-line tool that you can use to manage your AWS resources. You can install the AWS CLI by going to https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html.\r\n\r\n### Creating an EC2 Instance\r\nYou can use the AWS free tier to create an EC2 instance. To do this, go to the \"EC2\" section of the AWS Management Console and click on the \"Launch Instance\" button.\r\n\r\n\r\n### Connecting to Your EC2 Instance\r\nOnce you have created an EC2 instance, you can connect to it using SSH. You can do this by using the AWS CLI or a third-party SSH client.\r\n\r\n### Conclusion\r\nThe AWS free tier is a great way to get started with AWS. It allows you to create and use a variety of AWS resources for free. Once you have familiarized yourself with the AWS platform, you can decide whether to upgrade to a paid plan.\r\n\r\n### Additional Resources\r\nhttps://docs.aws.amazon.com/\r\nhttps://aws.amazon.com/free/\r\nhttps://aws.amazon.com/cli/\r\nhttps://en.wikipedia.org/wiki/Secure_Shell";
						const data = {title:"AWS Amazon Webservice",description:"Here is a sample of some basic Markdown syntax that can be used when writing Markdown content in Astro.",pubDate:new Date(1710111600000),heroImage:"/amazon.png"};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/User/Documents/astro-blog-latest/src/content/blog/aws.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
